apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: meta
spec:
  pipelineSpec:
    tasks:
    - name: meta-pipeline
      taskSpec:
        steps:
        - image: gcr.io/jenkinsxio/jx-boot:3.1.170
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables
        - image: gcr.io/kaniko-project/executor:debug-v1.3.0
          name: build-container-build
          resources: {}
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
